language: node_js
node_js:
  - 4
  - 6
  - 8

cache: yarn

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.25.4
  - yarn
  - yarn run bootstrap

script: 
  - yarn run build
  - yarn run test