git:
  depth: false

language: node_js
node_js:
  - 8
  - 10

cache: yarn

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.25.4
  - yarn
  - yarn run bootstrap

script:
  - yarn run build
  - yarn run test
  - if [ "$TRAVIS_BRANCH" = "master" ]; then $(yarn bin)/publish-if-not-published; fi
