version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: yarn run bootstrap
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: yarn run build
      - run: yarn run test
